# Project that we are testing

language: python

# Version of python to test
python:
  - "3.5"

# Install dependencies
install:
  - pip install -r requirements.txt
# Testing 
script:
  - nosetests --with-coverage --cover-package=tests 
  - coverage run --source=app -m nose && coverage report

after-sucess:
  - coveralls